---
name: Tracker

options:
  deploymentTarget:
      iOS: 13.6
  bundleIdPrefix: ru.practicum.yandex
  enableBaseInternationalization: true
  indentWidth: 4

include:
  - path: Config/xcodegen/targets.yaml
    relativePaths: false
  - path: Config/xcodegen/base_settings.yaml
    relativePaths: false

configs:
  Debug: debug
  Release: release

packages:
  Realm:
    url: https://github.com/realm/realm-swift.git
    version: 10.44.0
  Rswift:
    url: https://github.com/mac-cain13/R.swift
    version: 7.4.0
  swift-snapshot-testing:
    url: https://github.com/pointfreeco/swift-snapshot-testing
    version: 1.11.1

