---
settings:
  base:
    SWIFT_VERSION: 5.5
    DEBUG_INFORMATION_FORMAT: dwarf-with-dsym
    MTL_ENABLE_DEBUG_INFO: INCLUDE_SOURCE
    TARGETED_DEVICE_FAMILY: 1
    SUPPORTS_MACCATALYST: NO
  configs:
    Debug:
      SWIFT_ACTIVE_COMPILATION_CONDITIONS: ["$(inherited)", "DEBUG"]
      SWIFT_COMPILATION_MODE: incremental
    Release:
      SWIFT_COMPILATION_MODE: wholemodule
