name: iOS starter workflow

on:
  push:
  pull_request:
    branches: 
      - main
  workflow_dispatch:

jobs:
  build:
    name: Build 
    strategy:
      fail-fast: false
      matrix:
        macos:
          - 12
    runs-on: macos-${{ matrix.macos }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Show SDKs
        run: xcodebuild -showsdks 
      
      - name: Double-check Xcode.app selected
        run: xcode-select --print-path

      - name: Check xcodebuild version
        run: xcodebuild -version

      - name: Checkout ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.0'
          bundler-cache: true
          working-directory: 'ios'
      
      - name: fastlane build
        uses: maierj/fastlane-action@v3.0.0
        with:
        lane: 'beta'
        subdirectory: 'ios'
