name: iOS starter workflow

on:
  push:
  pull_request:
    branches: 
      - main
  workflow_dispatch:

jobs:
  build:
    name: Build 
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build
        run: |
          xcodebuild clean build \
          -project ./Tracker.xcodeproj \
          -scheme Tracker \
          -allowProvisioningUpdates -quiet
          -destination "platform=iOS Simulator,name=iPhone 11,OS=13.6" \
          PROVISIONING_PROFILE_SPECIFIER= -derivedDataPath /tmp/ddata
