name: iOS starter workflow

on:
  push:
  pull_request:
    branches: 
      - main
  workflow_dispatch:

jobs:
  build:
    name: Build 
    strategy:
      fail-fast: false
      matrix:
        macos:
          - 12
    runs-on: macos-${{ matrix.macos }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Show SDKs
        run: xcodebuild -showsdks 

      - name: Build
        run: |
          xcodebuild build \
          -project ./Tracker.xcodeproj \
          -scheme Tracker \
          -allowProvisioningUpdates \
          -verbose \
          -sdk iphoneos16.2 \
          -configuration Debug
