name: iOS starter workflow

on:
  push:
  pull_request:
    branches: 
      - main
  workflow_dispatch:

jobs:
  build:
    name: Build 
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build
        run: |
          xcodebuild build \
          -project ./Tracker.xcodeproj \
          -scheme Tracker \
          -allowProvisioningUpdates \
          -quiet \
          -derivedDataPath /tmp/ddata \
          -sdk iphoneos16.4
