name: iOS starter workflow

on:
  push:
  pull_request:
    branches: 
      - main
  workflow_dispatch:

jobs:
  build:
    name: Build 
    strategy:
      fail-fast: false
      matrix:
        macos:
          - 12
    runs-on: macos-${{ matrix.macos }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Show SDKs
        run: xcodebuild -showsdks 
      
      - name: Double-check Xcode.app selected
        run: xcode-select --print-path

      - name: Check xcodebuild version
        run: xcodebuild -version

      - name: Show list
        run: xcodebuild -list

      - name: Fastlane build
        run: fastlane beta
      # - name: Build
      #   uses: sersoft-gmbh/xcodebuild-action@v2
      #   with:
      #     project: Tracker.xcodeproj
      #     scheme: Tracker
      #     destination: platform=iOS Simulator
      #     action: build
 
